apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: le-staging
spec:
  acme:
    server: https://acme--staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-staging
    solvers:
    - http01:
        ingress:
          class: nginx
